version: '3.4'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
        - mongo_data:/data/db
volumes:
  mongo_data: 